/* Generated By:JavaCC: Do not edit this line. ParseZPLConstants.java */
package zplviewer.javacc;

public interface ParseZPLConstants {

  int EOF = 0;
  int C_XA = 5;
  int C_XZ = 6;
  int C_MC = 7;
  int C_LH = 8;
  int C_FO = 9;
  int C_FT = 10;
  int C_FS = 11;
  int C_LR = 12;
  int C_FW = 13;
  int C_CF = 14;
  int C_CI = 15;
  int C_PR = 16;
  int C_PO = 17;
  int C_PM = 18;
  int C_GB = 19;
  int C_PQ = 20;
  int C_BC = 21;
  int C_BY = 22;
  int C_B3 = 23;
  int C_LL = 24;
  int C_FR = 25;
  int C_SN = 26;
  int C_XG = 27;
  int C_GS = 28;
  int C_MT = 29;
  int C_MM = 30;
  int C_MN = 31;
  int C_MD = 32;
  int C_A = 33;
  int C_AO = 34;
  int C_FD = 35;
  int C_ID = 36;
  int DIGIT = 37;
  int NUMBER = 38;
  int CHAR = 39;
  int FLOAT = 40;
  int STRING = 41;

  int DEFAULT = 0;
  int VALUE = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"^XA\"",
    "\"^XZ\"",
    "<C_MC>",
    "\"^LH\"",
    "\"^FO\"",
    "\"^FT\"",
    "\"^FS\"",
    "\"^LR\"",
    "\"^FW\"",
    "\"^CF\"",
    "\"^CI\"",
    "\"^PR\"",
    "\"^PO\"",
    "\"^PM\"",
    "\"^GB\"",
    "\"^PQ\"",
    "\"^BC\"",
    "\"^BY\"",
    "\"^B3\"",
    "\"^LL\"",
    "\"^FR\"",
    "\"^SN\"",
    "\"^XG\"",
    "\"^GS\"",
    "\"^MT\"",
    "\"^MM\"",
    "\"^MN\"",
    "\"^MD\"",
    "\"^A\"",
    "<C_AO>",
    "\"^FD\"",
    "\"^ID\"",
    "<DIGIT>",
    "<NUMBER>",
    "<CHAR>",
    "<FLOAT>",
    "<STRING>",
    "\",\"",
  };

}
